import { Theme } from "../theme.slint";

export component MinimalProgressBar {
    in property <float> progress: 0.0; // 0.0 to 1.0
    in property <bool> active: false;

    height: 4px;

    Rectangle {
        background: Theme.surface-active;
        border-radius: 2px;
        clip: true;

        if root.active : Rectangle {
            width: parent.width * max(0.0, min(1.0, root.progress));
            height: 100%;
            x: 0;
            background: Theme.accent;
            border-radius: 2px;

            animate width { duration: 150ms; }
        }
    }
}
